version: "1.0"
name: android-release
displayName: Android自动构建发布

stages:
  - name: build-and-release
    displayName: 构建并发布
    strategy: naturally
    trigger: auto
    steps:
      - step: build@android
        name: build-apk
        displayName: 构建 APK
        jdkVersion: "17"
        gradleVersion: "9.3"
        buildToolsVersion: 36.1.0
        ndkVersion: 28.2.13676358
        commands:
          - chmod +x gradlew
          - ./gradlew --no-daemon -PreleaseBuildNumber="$(date +%s)" clean lintRelease assembleRelease
        artifacts:
          - name: ANDROID_RELEASE
            path:
              - app/build/outputs/apk/release
            type: .tar.gz
        caches:
          - ~/.gradle/caches
        strategy:
          retry: "0"
          resource:
            cpu: "2"
            memory: "4"

triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ""
      precise:
        - main
      include: []

notify: []

variables:
  UPDATE_REPOSITORY: Sibingwei/HuangguoPlayerAndroid